import { useCallback, useEffect, useState } from "react";
import { ApiError, api, setCsrfToken, setUnauthorizedHandler } from "./api";
import type { SessionInfo } from "./types";
import { Badge } from "./components/common";
import { Live } from "./views/Live";
import { Queue } from "./views/Queue";
import { Health } from "./views/Health";

type View = "live" | "queue" | "health";

function parseHash(hash: string): { view: View; id: string | null } {
  const [, view, id] = hash.replace(/^#/, "").split("/");
  if (view === "queue") return { view, id: id ? decodeURIComponent(id) : null };
  if (view === "health") return { view, id: null };
  return { view: "live", id: null };
}

export function Login({ onSignedIn }: { onSignedIn: (s: SessionInfo) => void }) {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    setBusy(true);
    setError(null);
    try {
      onSignedIn(await api.post<SessionInfo>("/api/session", { username, password }));
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Sign-in failed");
    } finally {
      setPassword("");
      setBusy(false);
    }
  };
  return (
    <div className="login panel">
      <h1 style={{ marginBottom: 4 }}>Fraud decisioning console</h1>
      <p className="muted small" style={{ marginTop: 0 }}>
        Local deployment · simulated data. Accounts are created with <code>make dashboard-user</code>.
      </p>
      <form onSubmit={submit}>
        <label>Username<input type="text" autoComplete="username" value={username} onChange={(e) => setUsername(e.target.value)} required /></label>
        <label>Password<input type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>
        <button className="btn primary" type="submit" disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button>
        {error && <div className="banner bad" role="alert">{error}</div>}
      </form>
    </div>
  );
}

export function App() {
  const [session, setSession] = useState<SessionInfo | null>(null);
  const [checking, setChecking] = useState(true);
  const [route, setRoute] = useState(() => parseHash(window.location.hash));

  const signedIn = useCallback((s: SessionInfo | null) => {
    setCsrfToken(s?.csrf_token ?? null);
    setSession(s);
  }, []);

  useEffect(() => {
    setUnauthorizedHandler(() => signedIn(null));
    api.get<SessionInfo>("/api/session")
      .then(signedIn)
      .catch(() => signedIn(null))
      .finally(() => setChecking(false));
    const onHash = () => setRoute(parseHash(window.location.hash));
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, [signedIn]);

  const go = (view: View, id: string | null = null) => {
    window.location.hash = id ? `/${view}/${encodeURIComponent(id)}` : `/${view}`;
  };
  const signOut = async () => {
    try { await api.delete("/api/session"); } finally { signedIn(null); }
  };

  if (checking) return <div className="state">Loading…</div>;
  if (!session) return <Login onSignedIn={signedIn} />;

  const tabs: [View, string][] = [["live", "Live activity"], ["queue", "Investigation"], ["health", "Model & system health"]];
  return (
    <div className="shell">
      <header className="topbar">
        <h1>Fraud decisioning console</h1>
        <Badge tone="info" title="All transactions are generated by the project's simulator">Simulated data</Badge>
        <Badge title="Runs on this machine only; not a production service">Local deployment</Badge>
        <nav className="tabs" role="tablist" aria-label="Views">
          {tabs.map(([view, label]) => (
            <button key={view} role="tab" className="tab" aria-selected={route.view === view} onClick={() => go(view)}>{label}</button>
          ))}
        </nav>
        <span className="spacer" />
        <span className="muted small">{session.analyst} ({session.role})</span>
        <button className="btn" onClick={signOut}>Sign out</button>
      </header>
      <main>
        {route.view === "live" && <Live onOpen={(id) => go("queue", id)} isAdmin={session.role === "admin"} />}
        {route.view === "queue" && <Queue selected={route.id} onSelect={(id) => go("queue", id)} />}
        {route.view === "health" && <Health />}
      </main>
    </div>
  );
}
