"""Compare the OpenML and Kaggle copies of the ULB credit-card data, cell by cell.

    python scripts/compare_ulb_sources.py

Inputs (git-ignored; `python -m fraudplat.external.ulb fetch --source openml` and `--source
kaggle`): the OpenML ARFF and the Kaggle `archive.zip` / `creditcard.csv` in
`data/external/ulb-creditcard/`. Matching published counts are not
taken as evidence of identical data: the comparison checks column names and order, row and label
counts, every cell as text (quotes removed) and as a parsed float64, row order, and, if rows are
not aligned, whether the two are the same multiset of rows. Writes the aggregate result (no row
data) to `reports/external/ulb/source_comparison.json` and renders `source_comparison.md`.
"""

from __future__ import annotations

import hashlib
import io
import json
import sys
from pathlib import Path
from typing import Any

import polars as pl

from fraudplat.external.ulb import parse_arff, parse_csv

OPENML = Path("data/external/ulb-creditcard/creditcard.arff")
KAGGLE = Path("data/external/ulb-creditcard")
OUT = Path("reports/external/ulb/source_comparison.json")


def digest(path: Path, algorithm: str) -> str:
    h = hashlib.new(algorithm, usedforsecurity=False)
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def openml_text() -> tuple[list[str], pl.DataFrame]:
    names, lines = [], OPENML.read_text().splitlines()
    for i, line in enumerate(lines):
        low = line.strip().lower()
        if low.startswith("@attribute"):
            names.append(line.split()[1].strip("'\""))
        elif low.startswith("@data"):
            body = "\n".join(ln for ln in lines[i + 1 :] if ln.strip()).replace("'", "")
            schema = dict.fromkeys(names, pl.Utf8)
            return names, pl.read_csv(io.StringIO(body), has_header=False, schema=schema)
    raise SystemExit("no @DATA section in the ARFF")


def kaggle_text() -> tuple[list[str], pl.DataFrame]:
    path = KAGGLE / "creditcard.csv"
    header = [c.strip('"') for c in path.open().readline().strip().split(",")]
    frame = pl.read_csv(path, infer_schema=False)  # all Utf8; CSV quotes removed by the parser
    return header, frame


def kaggle_metadata() -> dict[str, Any]:
    meta = json.loads((KAGGLE / "kaggle_metadata.json").read_text())
    return {
        "dataset": meta["ref"],
        "owner": f"{meta['ownerName']} ({meta['ownerRef']})",
        "version": meta["currentVersionNumber"],
        "version_updated": meta["lastUpdated"],
        "license": meta["licenseName"],
        "downloaded_at": (KAGGLE / "kaggle_downloaded_at.txt").read_text().strip(),
        "download": "https://www.kaggle.com/api/v1/datasets/download/mlg-ulb/creditcardfraud "
        "(Kaggle's official endpoint; no sign-in was requested)",
    }


def render(r: dict[str, Any]) -> str:
    o, k, cells = r["openml"], r["kaggle"], r["cells"]
    lines = [
        "# ULB credit-card data: OpenML and Kaggle copies compared",
        "",
        "Generated by `python scripts/compare_ulb_sources.py` from `source_comparison.json`. "
        "No row-level data is committed.",
        "",
        "| | OpenML (used by the original benchmark) | Kaggle (owner-listed source) |",
        "|---|---|---|",
        f"| Dataset | OpenML 1597 v1 | `{k['dataset']}` v{k['version']} (updated "
        f"{k['version_updated'][:10]}), owner {k['owner']} |",
        f"| File | `creditcard.arff` | `creditcard.csv` in `archive.zip` (downloaded "
        f"{k['downloaded_at']}) |",
        f"| Checksum | MD5 `{o['md5']}`; SHA-256 `{o['sha256']}` | "
        f"CSV SHA-256 `{k['csv_sha256']}`; "
        f"CSV MD5 `{k['csv_md5']}`; archive SHA-256 `{k['archive_sha256']}` |",
        '| Licence stated | "Public" (not a licence) | ODbL v1.0 (database), DbCL v1.0 '
        f"(contents); Kaggle API `licenseName`: {k['license']} |",
        f"| Rows | {r['rows']['openml']:,} | {r['rows']['kaggle']:,} |",
        f"| Labels 0 / 1 | {r['labels']['openml']['0']:,} / {r['labels']['openml']['1']} | "
        f"{r['labels']['kaggle']['0']:,} / {r['labels']['kaggle']['1']} |",
        "",
        "## Result",
        "",
        f"* Columns: same names and order ({len(r['columns']['openml'])} columns: "
        f"{', '.join(r['columns']['openml'][:3])}, …, Amount, Class): "
        f"{'yes' if r['columns']['same_names_and_order'] else 'no'}.",
        f"* Cells compared: {cells['total']:,}. Text differences (quotes removed): "
        f"{cells['text_differences']}; differences after parsing to float64: "
        f"{cells['float64_differences']}; class-label differences: "
        f"{cells['class_label_differences']}.",
        f"* Row order: row-by-row identical: "
        f"{'yes' if r['row_order']['row_by_row_identical_after_parsing'] else 'no'}.",
        "* Formatting differs only in quoting: the ARFF quotes the class values (`'0'`), the CSV "
        'quotes its header and class values (`"0"`). The numbers are written identically in '
        "both, including the one value in exponent notation (`1e+05`), so parsing introduces no "
        "difference. "
        f"Loader output (`ulb.parse_arff` vs `ulb.parse_csv`) identical: "
        f"{'yes' if r['loader_output_identical'] else 'no'}.",
        "",
        "Conclusion: the data rows are identical. The original benchmark was run on the OpenML "
        "copy and its provenance is recorded as such; the Kaggle listing is now the preferred "
        "acquisition route because it is the owner-listed source and states the licence.",
        "",
        "Contains information from [Credit Card Fraud Detection]"
        "(https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud), which is made available here "
        "under the [Open Database License (ODbL)](https://opendatacommons.org/licenses/odbl/1-0/).",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    o_names, o = openml_text()
    k_names, k = kaggle_text()
    result: dict[str, Any] = {
        "openml": {
            "file": "creditcard.arff (OpenML 1597 v1)",
            "md5": digest(OPENML, "md5"),
            "sha256": digest(OPENML, "sha256"),
        },
        "kaggle": {
            "file": "creditcard.csv in archive.zip (Kaggle mlg-ulb/creditcardfraud v3)",
            "archive_sha256": digest(KAGGLE / "archive.zip", "sha256"),
            "csv_md5": digest(KAGGLE / "creditcard.csv", "md5"),
            "csv_sha256": digest(KAGGLE / "creditcard.csv", "sha256"),
            **kaggle_metadata(),
        },
        "columns": {
            "openml": o_names,
            "kaggle": k_names,
            "same_names_and_order": o_names == k_names,
        },
        "rows": {"openml": o.height, "kaggle": k.height},
    }
    if o_names != k_names or o.height != k.height:
        OUT.write_text(json.dumps(result, indent=2) + "\n")
        print("schema or row count differs; see", OUT)
        return 1
    labels = {
        name: {v: int(n) for v, n in f["Class"].value_counts().sort("Class").iter_rows()}
        for name, f in (("openml", o), ("kaggle", k))
    }
    result["labels"] = labels
    numeric = [c for c in o_names if c != "Class"]
    text_diff = {c: int((o[c] != k[c]).sum()) for c in o_names}
    of = o.select(pl.col(c).cast(pl.Float64) for c in numeric)
    kf = k.select(pl.col(c).cast(pl.Float64) for c in numeric)
    float_diff = {c: int((of[c] != kf[c]).sum()) for c in numeric}
    examples: list[dict[str, str]] = []
    for c in numeric:
        if text_diff[c] and len(examples) < 5:
            mask = o[c] != k[c]
            pairs = pl.DataFrame({"openml": o[c].filter(mask), "kaggle": k[c].filter(mask)})
            examples += [
                {"column": c, "openml": a, "kaggle": b} for a, b in pairs.head(2).iter_rows()
            ]
    result["cells"] = {
        "total": o.height * len(o_names),
        "text_differences": sum(text_diff.values()),
        "text_differences_by_column": {c: n for c, n in text_diff.items() if n},
        "float64_differences": sum(float_diff.values()),
        "float64_differences_by_column": {c: n for c, n in float_diff.items() if n},
        "class_label_differences": text_diff["Class"],
        "text_difference_examples": examples,
    }
    aligned = sum(float_diff.values()) == 0 and text_diff["Class"] == 0
    result["row_order"] = {"row_by_row_identical_after_parsing": aligned}
    if not aligned:
        key = [*numeric, "Class"]
        a = of.with_columns(o["Class"]).sort(key)
        b = kf.with_columns(k["Class"]).sort(key)
        result["row_order"]["same_multiset_of_rows"] = a.equals(b)
    result["identical_data"] = aligned
    arff_frame = parse_arff(OPENML.read_text())
    csv_frame = parse_csv((KAGGLE / "creditcard.csv").read_bytes())
    result["loader_output_identical"] = arff_frame.equals(csv_frame)
    OUT.write_text(json.dumps(result, indent=2) + "\n")
    OUT.with_suffix(".md").write_text(render(result))
    print(json.dumps({k2: result[k2] for k2 in ("rows", "labels", "row_order")}, indent=1))
    print(json.dumps({k2: v for k2, v in result["cells"].items()}, indent=1)[:1500])
    return 0


if __name__ == "__main__":
    sys.exit(main())
